baseURL = 'https://paulmazeau.github.io/quickstart'
languageCode = 'en-us'
title = 'Le blog de paul'
theme = 'hextra'

[[menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/about"
weight = 3
